name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npx --yes firebase-tools@15.30.0 deploy --project ppradyoth --only hosting:on-device-ai-app-starter-kit --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
